### PR TITLE
fix preamble checkbox dissapearing when you backspace the whole thing

### LINKED ISSUE #1788: Backspacing preamble all the way in mapper makes it go away

### PR DESCRIPTION
**Pull request by kavigupta**
Resolve #1788

### CODE REVIEW

File: react/src/mapper/settings/map-uss.ts [hunk 1]
```diff
@@ -27,29 +32,44 @@ const pMap = { type: 'opaque', name: 'pMap', allowCustomExpression: false } sati
...
+        return undefined
+    }
+    const expr = stmt.value
+    if (expr.type === 'customNode') {
+        return expr
+    }
+    if (expr.type === 'autoUXNode') {
+        if (expr.expr.type === 'customNode') {
+            // really not sure why typescript can't figure this out, but it can't
+            return expr as PreambleAutoUXNode
```
Comment (lukebrody) [inline react/src/mapper/settings/map-uss.ts]:
```suggestion
            return { ...expr, expr: expr.expr }
```
Type narrowing on affects the exact expression that is narrowed :sob:

File: react/src/mapper/settings/PreambleEditor.tsx [hunk 2]
```diff
@@ -15,34 +24,40 @@ export function PreambleEditor({
...
-    preamble: UrbanStatsASTExpression & { type: 'customNode' }
-    setPreamble: (conditionExpr: UrbanStatsASTExpression & { type: 'customNode' }) => void
+    preamble: PreambleNode
+    setPreamble: (value: PreambleNode) => void
     typeEnvironment: TypeEnvironment
     errors: EditorError[]
     blockIdent: string
 }): ReactNode {
-    const [showPreamble, setShowPreamble] = useState(preamble.originalCode.trim() !== '')
+    const [showPreamble, setShowPreamble] = useState(shouldShowPreamble(preamble))
```
Comment (lukebrody) [inline react/src/mapper/settings/PreambleEditor.tsx]: Do we need `useState`? Why not just store the state in the USS rather than keeping it in two places?
