### PR TITLE
Fix articles with many /

### LINKED ISSUE #759: SPA broke link sanitization
I think this bug was introduced by SPA. Following tests fail:

1. Type into the address bar "victory manor" then hit enter
2. Go to https://urbanstats.org/article.html?longname=Savannah+city%2C+Georgia%2C+USA&universe=North+America&s=FGeQWrY52z2nuF and then click on the button containing "victory manor". 
3. Go to https://urbanstats.org/statistic.html?statname=Population&article_type=Neighborhood&start=10341&amount=20&universe=North+America and click the link containing "victory manor".

I'm sure there's others I've missed. This can probably be fixed in fetching data links

### PR DESCRIPTION
**Pull request by lukebrody**
Closes #759 

This was always broken

### CODE REVIEW

File: react/src/navigation/navigator.tsx [hunk 1]
```diff
@@ -187,15 +187,15 @@ export function urlFromPageDescriptor(pageDescriptor: ExceptionalPageDescriptor)
         case 'article':
             pathname = '/article.html'
             searchParams = {
-                longname: sanitize(pageDescriptor.longname),
```
Comment (lukebrody) [inline react/src/navigation/navigator.tsx:190]: @kavigupta This is going to break some recently shared links (it was a mistake in the implementation). Only those that need to be sanitized though, which should be few

Comment (kavigupta) [reply react/src/navigation/navigator.tsx:190]: Yeah that's fine
